### ISSUE TITLE
DSS Exception: Unknown parameter

### ISSUE THREAD

**Issue by HeatherAChang** [dss-extensions/OpenDSSDirect.py#101]
### Versions

- [] Python version: 3.9.5 
- [] Python architecture: x64
- [] Operating system and version: Centos 7
- [] OpenDSSDirect.py version number: 0.10.7.post1

### Bug

Open DSS is giving me the following exception when I run it on version 0.10.7.post1. However, when I run the same .DSS files using version Open DSS version 0.3.7, I do not get any exceptions. 

```  
File "/home/user/.conda/envs/envName/lib/python3.9/site-packages/dsspy-2.0-py3.9.egg/PyDSS/modes/QSTS.py", line 36, in __init__
    self._dssSolution.Mode(2)
File "/home/user/.conda/envs/nameEnv/lib/python3.9/site-packages/opendssdirect/Solution.py", line 330, in Mode
    CheckForError(lib.Solution_Set_Mode(Mode))
File "/home/user/.conda/envs/nameEnv/lib/python3.9/site-packages/dss/_cffi_api_util.py", line 81, in CheckForError
    raise DSSException(error_num, self._get_string(self._lib.Error_Get_Description()))
dss._cffi_api_util.DSSException: (130, 'Unknown parameter "%SeriesRL" for Set Command ')
                                                                                      
```

**Comment by kdheepak** [comment]
Hi @HeatherAChang, this wasn’t on Windows, was it? The issue template’s operating system is Windows but the stack trace is POSIX like.

**Comment by HeatherAChang** [comment]
Hi @kdheepak, you're right! I just updated my issue to show it was Centos 7

**Comment by PMeira** [comment]
> Unknown parameter "%SeriesRL" for Set Command 

I think this is self-explaining. There's probably an issue in the .DSS scripts. `%SeriesRL` is a valid property only for loads:

https://github.com/dss-extensions/dss_capi/blob/master/docs/dss_properties.md#load-properties

As to why the error show up there, see the first part of https://github.com/dss-extensions/OpenDSSDirect.py/issues/100#issuecomment-866451518

**Comment by kdheepak** [comment]
Ah, thanks for the comment @PMeira. I think @HeatherAChang wasn’t getting an error with an older version of OpenDSSDirect. This explains why that was the case.

**Comment by HeatherAChang** [comment]
Yes @kdheepak is correct. When I use opendssdirect version 0.3.7 with the same .DSS scripts, it runs without any problems.  I updated my problem to reflect this.

**Comment by PMeira** [comment]
@HeatherAChang You can try v0.3.7 and manually check if there are any pending errors through [`opendssdirect.Error.Number()`](https://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.Error.Number). It's likely the error was just being ignored.
