### ISSUE TITLE
Update dss-python dependency

### ISSUE THREAD

**Issue by charraig** [dss-extensions/OpenDSSDirect.py#112]
### Versions

- [x] Python version: 3.9.10
- [x] Python architecture: x64
- [x] Operating system and version: Mac Monterey 12.0.1 M1 Chip
- [x] OpenDSSDirect.py version number: 0.6.1

### Feature Request

`dss-python` just released version 0.12.0b2 to support the Mac M1 ARM chips, but `setup.py` includes enforcement for version 0.10.7.post1. Could you modify this dependency requirement to be "^0.10" so that dependency managers (e.g. poetry) allow for the 0.12 version?

**Comment by charraig** [comment]
I see there is already a PR. +1 for merge! #110

**Comment by PMeira** [comment]
@charraig For engine updates, usually we merge just before the release. This next version (based on DSS C-API 0.12) is special since a lot of things were changed in the engine internals, hence the extended test period. It seems good though, so it shouldn't take much longer.

About M1/ARM64, I'm not able to test it, so please let us know if you find any breaking issue. If you're able to run ODD.py's updated tests from the PR branch https://github.com/dss-extensions/OpenDSSDirect.py/tree/dss_python-0.12.0, it should be OK.

**Comment by charraig** [comment]
Hi @PMeira, thanks for the help! I was finally able to give this a test, found an import issue, I put a comment over at: https://github.com/dss-extensions/dss_python/issues/41#issuecomment-1098346278

**Comment by charraig** [comment]
@PMeira I also tested the 0.12.0.b4 `dss-python` version from here, all 59 tests passed once I moved the import statement of `test_evaluate_expression.py` into the function itself. Not sure if that's the proper fix, but I was getting a "module not found" error when it was outside the function.

**Comment by PMeira** [comment]
@charraig That's great news!
I added a commit to move the import per your comment. Kind of weird that it doesn't happen in the CI etc., but that doesn't affect much (that file doesn't use the DSS engine, and might be removed sooner or later after the new API changes land).

**Comment by qhuang0411** [comment]
I have almost the same setup as @charraig, and my dependency manager poetry failed to install opendssDirect.py=0.6.1 due to "Unable to find installation candidates for dss-python (0.10.7.post1)", any suggestion to address this?

**Comment by charraig** [comment]
Hi @qhuang0411, I put this line in my poetry package toml file to call the specific branch that has the working update:

`'OpenDSSDirect.py' = { git = "https://github.com/dss-extensions/OpenDSSDirect.py.git", branch = "dss_python-0.12.0"}`

See if that works for you.

`

**Comment by PMeira** [comment]
@charraig @qhuang0411 New packages released on PyPI
