### ISSUE TITLE
Daily is not present in PVSystems. 

### ISSUE THREAD

**Issue by jd-lara** [dss-extensions/OpenDSSDirect.py#42]
I noticed `dss.PVSystem.Daily` is not available to add an irradiance time series to a PV system. Can this be made available to enable time simulations including solar panels?

**Comment by PMeira** [comment]
There are a lot of fields missing from the direct interface. For the moment you'd have to resort to the text/`run_command` interface.

I can work on PVSystem next time I'm working on the DSS C-API code, then we can expose it OpenDSSDirect.py. I added it to https://github.com/PMeira/dss_capi/issues/11 -- I'll try to make a single pull request with all these recent additions.
