### ISSUE TITLE
Change load at specific bus of the network

### ISSUE THREAD

**Issue by saimunikoti** [dss-extensions/OpenDSSDirect.py#72]
### Versions

- [ ] Python version: <(3.7)>
- [ ] Python architecture: 
- [ ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Support Question

<I am using OpenDSSDirect.py for load flow analysis. How can I change the load at specific bus without changing the load in dss file? I have to do monte carlo simulation for load flow analysis, but the load at specific bus will be different for each simulation. One way to tackle this problem is to change the load of the bus in the dss file. But this is not feasible, as every time I have to manually change the load in dss file and then run the simulation. Is there a python command which can change the load at desired bus ? 
Thanks in advance.>

**Comment by PMeira** [comment]
@saimunikoti You could

1) Activate the load (by [name](http://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.Loads.Name) or [index](http://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.Loads.Idx)), then use [CktElement.BusNames](http://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.CktElement.BusNames) to set the new bus.

or

2) Use the [text interface](http://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.Text.Command) or [run_command](http://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.utils.run_command) to pass any DSS command, i.e., you could pass a string such as `edit load.myload bus=newbus`.

Besides the slightly different organization of the functions in OpenDSSDirect.py, it works very much like the official OpenDSS. If you don't have a copy of the OpenDSS documentation, get it here:

https://sourceforge.net/p/electricdss/code/HEAD/tree/trunk/Version7/Distrib/Doc/
