### ISSUE TITLE
Cannot find power flow value for each line

### ISSUE THREAD

**Issue by MingyueHe** [dss-extensions/OpenDSSDirect.py#73]

**Comment by tshort** [comment]
You'll need to be a bit more specific here. Tell us what you tried and what didn't work.

**Comment by MingyueHe** [comment]
I want to obtain the result of the power flow value for each line. I use CktElement module. However, I cannot find a way to obtain the active power like what I did for obtaining the output of generators.

**Comment by tshort** [comment]
I'm not at a computer to try it, but have you tried [CktElement.Powers](https://dss-extensions.org/OpenDSSDirect.py/opendssdirect.html#opendssdirect.CktElement.Powers)? Should be able to use the real part of that.
