### ISSUE TITLE
Support New OpenDSS Objects?

### ISSUE THREAD

**Issue by qlong2** [dss-extensions/OpenDSSDirect.py#75]
### Versions
- [ ] Python version: 
- [ ] Python architecture: 
- [ ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Feature Request

Recently the OpenDSS released several new OpenDSS objects for PV system, inverter control, storage and storage controller with new object names (for example, PVSystem2). Some of the issues with original OpenDSS objects are fixed in the new version. However, my python script with the OpenDSSDirect interface seems not to be able to compile the model with these new objects. I wonder if the current version of OpenDSSDirect supports those new objects yet. Thank you.

**Comment by qlong2** [comment]
Python version: 2.7.16
Python architecture: x64
Operating system and version: windows 10
OpenDSSDirect.py version number: 0.3.7

**Comment by PMeira** [comment]
No, they're no available yet. Adding them right now is not the best idea. 

Those new components were just added (couple of weeks ago, during the holidays). I'd wait a month or two so other users (and EPRI) have time to experiment and provide feedback directly on the official OpenDSS.

**Comment by PMeira** [comment]
@qlong2 It seems that even in the upstream OpenDSS those models have not been fully released yet, see https://sourceforge.net/p/electricdss/discussion/experts/thread/20a7da4968/#b9ed

**Comment by qlong2** [comment]
@PMeira Your answer makes a lot of sense. Also I found this post very useful. Thank you for your help.

**Comment by PMeira** [comment]
@qlong2 The next ODD.py release should include a preview of the new components, but testing them still show some issues even in the latest official OpenDSS -- as such, we can't properly validate them,  consider them experimental. They also don't have dedicate API functions yet.

**Comment by qlong2** [comment]
Thank you @PMeira for the update! I understand that the model validation is a time-consuming process. But can't wait to give it a try and thank you for the good work!

> @qlong2 The next ODD.py release should include a preview of the new components, but testing them still show some issues even in the latest official OpenDSS -- as such, we can't properly validate them, consider them experimental. They also don't have dedicate API functions yet.

**Comment by PMeira** [comment]
@qlong2 Just to confirm, the new models are enabled by default since OpenDSS 9.0 and our latest release: https://github.com/dss-extensions/OpenDSSDirect.py/releases/tag/v0.5.0

For our release, you can toggle the old components if necessary, but the default ones are now the new models (previously PvSystem2, Storage2...) just like in OpenDSS 9.
