### ISSUE TITLE
update dss_python version from requirements

### ISSUE THREAD

**Issue by armandokeller** [dss-extensions/OpenDSSDirect.py#83]
### Versions

- [3.8.2] Python version: 
- [x86] Python architecture: 
- [Windows 10 pro  1909 build 18363.900 ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Feature Request
Update the required version of dss_python, or the verification to greater than instead of equal.
The current required version of dss_python (0.10.1) is not available in pip (the available versions are 0.10.4 and 0.10.5).

![image](https://user-images.githubusercontent.com/1762410/84450680-4cc67d00-ac27-11ea-90ae-6eda40c012b5.png)

**Comment by PMeira** [comment]
@armandokeller A new package was tested and uploaded, tagged as v0.4.0. Note that it includes other changes besides DSS Python's version: https://github.com/dss-extensions/OpenDSSDirect.py/releases/tag/v0.4.0
